### ISSUE TITLE
Does now work on Ventura 13.1 with Chrome 118.0.5993.70

### ISSUE THREAD

**Issue by sboeser** [lemnos/chrome-session-dump#8]
Here is the error message I get:
```
panic: open /Users/<user>/.config/chrome: no such file or directory

goroutine 1 [running]:
main.parse(0xc000080080, 0x1d, 0x0, 0x0, 0x111ca60)
	/home/qpls/projects/chrome-session-dump/chrome-session-dump.go:248 +0x1a4f
main.main()
	/home/qpls/projects/chrome-session-dump/chrome-session-dump.go:542 +0x4a8

```

**Comment by aspiers** [comment]
Probably the same issue as with https://github.com/lemnos/chrome-session-dump/issues/9#issuecomment-2323310441

It needs to find the session file.  Try specifying it yourself instead of relying on auto-detect.
