### ISSUE TITLE
Does not work on Windows 10 with Chrome or Edge 119

### ISSUE THREAD

**Issue by djalilhebal** [lemnos/chrome-session-dump#9]
Executing `chrome-session-dump.exe` [v0.0.2](https://github.com/lemnos/chrome-session-dump/releases/tag/v0.0.2) outputs the following:
```
panic: open /.config/chrome: The system cannot find the path specified.

goroutine 1 [running]:
main.parse(0x50e67b, 0xf, 0x0, 0x0, 0x52c8c0)
        /home/qpls/projects/chrome-session-dump/chrome-session-dump.go:248 +0x1a63
main.main()
        /home/qpls/projects/chrome-session-dump/chrome-session-dump.go:542 +0x479
```

PS: I use both Edge and Chrome.

**Comment by m-alice** [comment]
Hello! I just used WSL for this.

Sorry, i'm dont wanna to tell, how to enable wsl for windows, that would lengthen the instructions too much.
Install Debian from **https://apps.microsoft.com/detail/9msvkqc78pk6**
Run it from the windows start menu and wait for the inner install ends
Create Linux user and password (any, you can just use one letter or digit for the both)
Update repositories list - **sudo apt update && sudo apt upgrade**
Install curl - **sudo apt install curl**
Install chrome-session-dump as it says in the readme
Install midnight commander - **sudo apt -y install mc**
Run midnight commander - **mc**
In the left panel, search for your chrome session files, usually it it the **/mnt/c/Users/yourwindowsname/AppData/Local/Microsoft/Edge/User Data/Default/Sessions**
In the right panel, go to **/home/yourlinuxname/.config**
Press F7 and create folder **Chrome**, and copy in this folder all files from the left panel (Apps_* Sessions_* Tabs_*)
When you in the right panel, press Ctrl+O and run **chrome-session-dump > test.txt**
You can use F3 for the fast view test.txt or copy this file back to the left panel (do not use Notepad please, this file may be too big)

**Comment by aspiers** [comment]
Looks like it's not expanding `$HOME` correctly in the Windows case:

https://github.com/aspiers/chrome-session-dump/blob/bbbe9c0e7cad882997f43f6b4c2c0089a0c0cc0a/chrome-session-dump.go#L594-L602

**Comment by aspiers** [comment]
Looks like it's not expanding `$HOME` correctly in the Windows case:

https://github.com/aspiers/chrome-session-dump/blob/bbbe9c0e7cad882997f43f6b4c2c0089a0c0cc0a/chrome-session-dump.go#L594-L602
